---
- name: 1. install Apache
  apt: name=apache2 state=present

- name: 2. install PHP 7.0
  apt: name=php7.0 state=present

- name: 3. install PHP module for Apache
  apt: name=libapache2-mod-php7.0 state=present

- name: 3. enable module PHP 7.0 in Apache
  apache2_module: name=php7.0 state=present

- name: 4. start Apache
  service: name=apache2 state=restarted enabled=yes

- name: 5. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664
