---
    - name: Install Nginx
      apt: pkg=nginx state=latest
      register: nginxinstalled
      notify:
          - nginx start

    - name: Add NGINX cofig
      copy:
        src: /etc/ansible/roles/nginx/files/index.html
        dest: /var/www/html/index.html

    - name: Add NGINX cofig
      when: nginxinstalled|success
      template: src={{ domain }}.conf dest=/etc/nginx/conf.d/{{ domain }}.conf owner=nginx group=nginx

    - name: Create Web Root
      when: nginxinstalled|success
      file: path={{ root }}  mode=775 state=directory owner=nginx group=nginx
      notify:
          - nginx restart
