---
  - name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
    raw: apt-get install python-minimal aptitude -y
  - name: Update apt cache
    apt: update_cache=yes
  - name: Upgrade
    apt:
      upgrade: yes

  - name: Install apache2
    apt: name=apache2 state=present
  - name: Copy site.conf to server
    template:
       src=siteansible.conf.j2
       dest=/etc/apache2/sites-available/site.conf
  - name: Remove 000-default.conf
    file:
      path=/etc/apache2/sites-enabled/000-default.conf
      state=absent
  - name: Remove /var/www/html directory
    file:
      path=/var/www/html
      state=absent
  - name: Copy html directory to server
    template:
       src=html/*
       dest=/var/www/html/*
       owner=root
       group=root
       mode=744
  - name: Create simlink site.conf
    file:
       src=/etc/apache2/sites-available/site.conf
       dest=/etc/apache2/sites-enabled/site.conf
       state=link
  - name: Enable apache2 module
    apache2_module: state=present name=userdir
    notify:
      - restart apache
  - name: Install mysql
    apt: name=mysql-server state=present
  - name: Install module python-mysqldb
    apt: name=python-mysqldb state=present
  - name: Create database
    mysql_db: name=site_database
                  state=present
    notify:
      - restart mysql
  - name: Install PHP
    apt: name=php state=present
  - name: Install paquetes php
    apt: name={{ item }}
         state=latest
    with_items:
          - php-mysql
          - libapache2-mod-php
